"""Derive per-feature input bounds from the training data.

Run this after changing the dataset and paste the emitted block into
app/schemas.py:

    python -m src.compute_bounds

The bounds are baked into the schema as literals rather than read at import
time on purpose: .dockerignore excludes data/ and the Dockerfile copies only
app/ and models/, so a schema that read the CSV at startup would crash the
container on boot.
"""

import pandas as pd

from .train import DATA_PATH

# Headroom above the observed maximum, so a reading somewhat beyond anything
# in the training set is still served rather than rejected.
BUFFER = 0.20

# ph is the exception: 0-14 is the definition of the scale, not an artefact of
# this sample, so it takes no buffer.
FIXED_BOUNDS = {"ph": (0.0, 14.0)}


def compute_bounds(buffer=BUFFER):
    df = pd.read_csv(DATA_PATH)
    X = df.drop("Potability", axis=1)

    bounds = {}
    for col in X.columns:
        if col in FIXED_BOUNDS:
            bounds[col] = FIXED_BOUNDS[col]
        else:
            bounds[col] = (0.0, round(float(X[col].max()) * (1 + buffer), 4))
    return bounds


def emit(bounds):
    width = max(len(c) for c in bounds)
    lines = []
    for col, (lo, hi) in bounds.items():
        note = "  # scale definition" if col in FIXED_BOUNDS else ""
        lines.append(
            f"    {col + ':':<{width + 1}} Optional[float] = "
            f"Field(None, ge={lo:g}, le={hi:g}){note}"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    b = compute_bounds()
    print(f"# generated by src/compute_bounds.py, buffer={BUFFER:.0%}")
    for col, (lo, hi) in b.items():
        print(f"#   {col:<16} le={hi:g}")
    print()
    print(emit(b))
